# Generated by Django 4.2.2 on 2023-06-06 00:11

from django.db import migrations


def create_post(apps, schema_editor):
    Post = apps.get_model('Blog', 'Post')
    Post.objects.create(title='Hola mundo', content='Este es el primer post de mi blog')
    Post.objects.create(title='Queso', content='El queso en la nevera se esta poniendo verde')

class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_post),
    ]
